name: synergy-core
channels:
  - conda-forge
dependencies:
  - numpy=1.20.1
  - pandas=1.2.4
  - pip=21.0.1
  - pyarrow=4.0.0
  - pyspark=3.2.1
  - python=3.8.10
  - wheel=0.36.2
  - requests=2.25.1
  - ipykernel=5.3.4
  # Dev and test requirements
  - requests-oauthlib=1.3.1
  - bandit=1.7.4
  - black=22.3.0
  - flake8=4.0.1
  - flake8-bugbear=22.3.23
  - dlint=0.12.0
  - flake8-comprehensions=3.8.0
  - flake8-polyfill=1.0.2
  - flake8-plugin-utils=1.3.2
  - flake8-pytest-style=1.6.0
  - pep8-naming=0.12.1
  - isort=5.10.1
  - mccabe=0.6.1
  - pycodestyle=2.8.0
  - pydocstyle=6.1.1
  - pyflakes=2.4.0
  - pylint=2.13.1
  - pytest=7.1.1
  - pytest-cov=3.0.0
  - pytest-xdist=2.5.0
  - pytest-forked=1.4.0
  - python-dotenv=0.20.0
  - pre-commit=2.16.0
  - pyyaml=6.0
  - filelock=3.7.1
  # automated documentation requirements
  - recommonmark=0.7.1
  - sphinx=4.5.0
  - sphinx-autobuild=2021.3.14
  - rstcheck=3.3.1

  - pip:
      - --trusted-host pypi.org --trusted-host files.pythonhosted.org
      - azure-cli-core==2.36.0
      - azure-cli-telemetry==1.0.6
      - azure-core==1.24.1
      - azure-identity==1.10.0
      - azure-mgmt-core==1.3.1
      - azure-common==1.1.28
      - azure-graphrbac==0.61.1
      - azure-mgmt-resource==21.1.0
      - azure-mgmt-storage==20.0.0
      - azure-multiapi-storage==0.9.0
      - azure-storage-blob==12.12.0
      - azure-storage-file-datalake==12.7.0
      - databricks-cli==0.16.4
      - setuptools==52.0.0
      - setuptools-scm==6.4.2
      - jupyter-client==6.1.12
      - jupyter-core==4.7.1
      - delta-spark==1.1.0
