[tool.black]
line-length = 99 # override black's default line-length
extend-exclude = '''
/(
  | src/delta
)/
'''

[tool.isort]
# make it compatible with black
profile = "black"
line_length = 99
sections = ["FUTURE", "STDLIB", "PYSPARK", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = "synergy"
known_local_folder = ["helpers"]
known_pyspark = "pyspark"x
skip_glob = ["src/delta/**"]